config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'search/find'

  get 'articles/new' => "articles#new"
  get 'topics/new' => "topics#new"

  resources :users, only: [:show, :update, :edit,] do
    resources :topics, only: [:create, :index, :destroy]
    resources :articles, only: [:new,:create, :index, :destroy]
  end

  root to: 'topics#index'
  resources :topics, only:[:index,:show, :new, :create, :edit, :update] do
    resources :articles, only: [:index, :show, :new, :create, :edit, :update] do
      post "vote", to: "articles#vote", as: :vote
      resources :comments, only: [:new, :create]
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :articles
   include PgSearch
  pg_search_scope :search_by_name_and_description, against: [ :name, :description ]

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_presence_of :user
  validates :name, presence: { message: "seems to be empty."},
            length: {minimum: 2}
  validates :description, length: {minimum:10, maximum: 200}, allow_blank: true
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/


  def set_user!(user)
    self.user_id = user.id

    self.save
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

def index
  @topics = policy_scope(Topic)
end

def show
  @topic = Topic.find(params[:id])
end


def new
@topic = Topic.new
authorize @topic
end

def create
  @topic = Topic.new(topic_params)
  @topic.set_user!(current_user)
  authorize @topic
    if @topic.save
      respond_to do |format|
        format.js
        format.html {redirect_to root_path}
        end
        flash[:notice] = 'Thank you, we will be in touch soon'
    else
      respond_to do |format|
        format.js { render }
        format.html { render :new }
      end
  end
end

def edit
  @topic = Topic.find(params[:id])
  authorize @topic
end

def update
  @topic = Topic.find(params[:id])
  @topic.update(topic_params)
  authorize @topic
  if @topic.save
    flash[:notice] = "Your topic has been updated"
     redirect_to topic_articles_path(@topic.id)
  else
    flash[:notice] = "Oops something went wrong"
  end
end



private

def topic_params
params.require(:topic).permit(:name,:picture,:user_id, :description)
end



end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/topics/_new.html.erb
<%if @topic.errors.any?%>
  <% @topic.errors.full_messages.each do |message| %>
    <% if message == "Name is too short (minimum is 2 characters)"%>
      <%@too_short = message%>
    <%elsif message == "Description is too short (minimum is 10 characters)"%>
      <%=@desciption = message%>
    <%else%>
      <%@other_error= message%>
    <%end%>
  <%end%>
<%end%>

  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="topicModalLabel">Suggest a topic</h4>
      </div>
      <br>
      <p class= "col-sm-11 col-sm-offset-1 text-align-center">Please let us know which topic you would like to curate. A short description would be handy. We will be in touch soon!</p>
      <br>
      <br>
      <br>
     <%= simple_form_for (@topic), html: {class: "form-horizontal newtopic-form", role:"form", remote:true} do |f| %>
        <div class="modal-body">
          <div class="form-group <%=@too_short%>">
            <%= f.label :name, class: "control-label col-sm-2" %>
            <div class="col-sm-8">
             <%= f.text_field :name, class: "form-control" %>
             <span class="help-block"><%=@too_short%> </span>
            </div>
          </div>

           <div class = "form-group <%=@desciption%>">
            <%= f.label :description, class: "control-label col-sm-2" %>
          <div class="col-sm-8">
            <%= f.text_field :description, class: "form-control" %>
            <span class="help-block"><%=@desciption%></span>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-2">
            <%= f.input :picture, class: "form-control" %>
          </div>
        </div>
      </div>

      <%= f.input :verified, as: :hidden, input_html: { value:false } %>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         <%= f.submit "Submit", class: "btn btn-success" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/topics/create.js.erb
<%if @topic.errors.any? %>

   $("#topicModal").html("<%= escape_javascript(render 'topics/new') %>");
   $(".Name").addClass("has-error");
   $(".Description").addClass("has-error");
   $("span").hide().fadeIn("slow");

<%else %>

  $('#topicModal').modal('hide').empty();
  window.location.reload();


<%end %>

app/views/topics/edit.html.erb
<div>

<h1>Topics</h1>

<%= simple_form_for (@topic) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.input :picture %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

</div>

app/views/topics/index.html.erb
<% content_for :body_class, "home" %>


<div class="banner">
  <div class= "title-container ">
    <div class="headline text-align-center">
      <h1 class="text-center">Topycal</h1>
      <h3 class="text-center" >Find the best articles</h3>
    </div>
  </div>
</div>


<div class="container home-background">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <div class="row">

        <% @topics.each do |topic| %>
        <% if topic.verified == true || topic.verified == nil  %>
          <div class= "col-xs-12 col-sm-6">
            <%= render 'shared/topictemp', topic: topic %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div>
<%if @topic.errors.any?%>
  <% @topic.errors.full_messages.each do |message| %>
    <% if message == "Name is too short (minimum is 2 characters)"%>
      <%=@too_short = message%>
    <%elsif message == "Description is too short (minimum is 10 characters)"%>
      <%=@desciption = message%>
    <%else%>
      <%@other_error= message%>
    <%end%>
  <%end%>
<%end%>

<h1>Topics</h1>

 <%= simple_form_for (@topic), html: {class: "form-horizontal newtopic-form", role:"form"} do |f| %>

  <div class="form-group <%=@too_short%>">
    <%= f.label :name, class: "control-label col-sm-2" %>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control"%>
      <span class="help-block"><%=@too_short%> </span>
    </div>
  </div>

  <div class = "form-group <%=@desciption%>">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control", rows:3 %>
      <span class="help-block"><%=@desciption%></span>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= f.input :picture, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
     <%= f.submit "Submit", class: "btn btn-success" %>
    </div>
  </div>
<%end%>
</div>



<%= content_for :after_js do %>

  <script type="text/javascript">
    $(document).ready(function() {
      $(".Name").addClass("has-error");
      $(".Description").addClass("has-error");
      $("span").hide().fadeIn("slow");

      });
  </script>
<%end%>

app/views/topics/new.js.erb
$("#topicModal").html("<%= escape_javascript(render 'topics/new') %>");

app/views/topics/show.html.erb
<% @topic.articles do |topic| %>
  <div>
      <p><%= article.title%></p>
  </div>

  <% end %>

  <%= link_to 'Add an article', new_topic_article_path(topic.id) %>