config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'search/find'

  get 'articles/new' => "articles#new"
  get 'topics/new' => "topics#new"

  resources :users, only: [:show, :update, :edit,] do
    resources :topics, only: [:create, :index, :destroy]
    resources :articles, only: [:new,:create, :index, :destroy]
  end

  root to: 'topics#index'
  resources :topics, only:[:index,:show, :new, :create, :edit, :update] do
    resources :articles, only: [:index, :show, :new, :create, :edit, :update] do
      post "vote", to: "articles#vote", as: :vote
      resources :comments, only: [:new, :create]
    end
  end
end

app/views/shared/_autherror.html.erb
 <div class="modal fade bs-example-modal-sm " id="authmodal" tabindex="-1"  aria-labelledby="mySmallModalLabel">

<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h5 class="modal-title">Almost there</h5>
    </div>
    <div class="modal-body">
      <p>Please sign in before suggesting a topic</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_autherror_article.html.erb
 <div class="modal fade bs-example-modal-sm " id="articlemodal" tabindex="-1"  aria-labelledby="mySmallModalLabel">

<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h5 class="modal-title">Almost there</h5>
    </div>
    <div class="modal-body">
      <p>Please sign in to add an article</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="alert">
    <a class="alert alert-info" href="#alert"><%= notice %></a>
  </div>
<% end %>

<% if alert %>
 <div id="alert">
    <a class="alert alert-warning" href="#alert"><%= alert %></a>
  </div>
<% end %>

<%= content_for :after_js do %>
  <script type="text/javascript">
     $(document).ready(function() {
      $("#alert").fadeOut(6000);
   });

  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <!-- <a href="/">
      <img src="logo.png" class="navbar-wagon-logo">
    </a> -->
    <h3 id="logo-left">Topycal</h3>

      <div class="navbar-wagon-pusher"></div>


    <%= form_tag(search_find_path,  method: :get, class: "navbar-wagon-search hidden-xs hidden-sm") do |f| %>
      <%= text_field_tag :search, '', class: 'navbar-wagon-search-input', placeholder: 'Search' %>
      <%= button_tag(type: "submit", class: "navbar-wagon-search-btn") do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>

        <div class="navbar-wagon-pushagain"></div>

    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to :controller => "devise/sessions", :action => "destroy" do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <% if user_signed_in? %>
    <%= button_to t(".top_call_to_action", default: "Suggest a topic"), new_topic_path, class: "navbar-wagon-item navbar-wagon-button btn", remote:true, data: {toggle: "modal", target: "#topicModal"}, method: :get%>
  </div>
    <%else%>
        <button type="button" class="navbar-wagon-item navbar-wagon-button btn" data-toggle="modal" data-target="#authmodal">Suggest a topic</button>
  <%end%>

</nav>

<div class="modal fade" id="topicModal" tabindex= "-1"   role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>

<%= render 'shared/autherror' %>

app/views/shared/_profilearticles.erb
<div class="post">
  <div class='post-upvote'>
    <div class="post-upvote-arrow" data-id=<%= article.id %> data-topicid= <%= article.topic_id %>></div>
      <%form_authenticity_token %>


      <!-- There's no form token sent for the click on the upvote button so you get an authenticity  issue. You need to find a way to either use the classicd html style or rewrite in form_tag style to make it work -->

    <div class='post-upvote-count'><%= article.votes %></div>
  </div>
  <div class='post-body'>

      <a href= "<%= article.url %>"  target="_blank"><p><%= "#{article.title}" %></p></a>


  </div>
  <div class='post-controls'>
    <i class="fa fa-comment post-control post-control-hidden"></i>
    <i class="fa fa-star post-control post-control-hidden"></i>
    <div class="post-control">

    </div>
  </div>
</div>

app/views/shared/_topictemp.html.erb
<!-- <hr class="cardline"> -->
<div class="card" id="topic-card">
  <div class="image-block">
    <%= image_tag(topic.picture.url, class: "card-img-top") %>
  </div>

  <div class="card-block">

    <h4 class="card-title"><%= link_to "#{topic.name}", topic_articles_path(topic.id)%></h4>

    <p class="card-text"><%= topic.description %></p>

  </div>
</div>

app/views/shared/_upvote.html.erb
  <div class="post">
    <div class='post-upvote'>
      <div class="post-upvote-arrow" data-id=<%= article.id %> data-topicid= <%= article.topic_id %>></div>
        <%form_authenticity_token %>



      <div class='post-upvote-count'><%= article.votes %></div>
    </div>
    <div class='post-body'>

        <a href= "<%= article.url %>"  target="_blank"><h5><%= "#{article.title}" %></h5></a>


    </div>
    <div class='post-controls'>
      <i class="fa fa-star post-control post-control-hidden"></i>
      <div class="post-control">
        <div class="user-badge-container ">
           <%= image_tag article.user.picture, class: "avatar" %>
          <!-- <div class="user-badge user-badge-black user-badge-bordered">M</div> -->
        </div>
      </div>
    </div>
  </div>

app/views/shared/_votingerror.html.erb
 <div class="modal fade bs-example-modal-lg " id="smallmodal" tabindex="-1"  aria-labelledby="mySmallModalLabel">

<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h5 class="modal-title">Friendly reminder</h5>
    </div>
    <div class="modal-body">
      <p>You have already upvoted this article. Why not checkout another article?</p>
      </div>
    </div>
  </div>
</div>